services:
  pbs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pbs
    hostname: pbs
    restart: unless-stopped
    ports:
      - "8007:8007/tcp"
      - "8007:8007/udp"
    command: ["proxmox-backup-proxy"]
    volumes:
      - pbs_config:/etc/proxmox-backup
      - pbs_varlib:/var/lib/proxmox-backup
      - pbs_logs:/var/log/proxmox-backup
      - pbs_datastore:/mnt/datastore

volumes:
  pbs_config:
  pbs_varlib:
  pbs_logs:
  pbs_datastore:
